<?php
/**
 * Prospect Digital — XML sitemap generator
 * ---------------------------------------------------------------------------
 * Outputs /sitemap.xml for search engines.
 * Two ways to serve it:
 *   1. With Apache + mod_rewrite: root .htaccess maps /sitemap.xml here.
 *   2. Without mod_rewrite: point your sitemap URL at /sitemap.xml.php directly,
 *      or run this file once from the command line and save the output:
 *          php sitemap.xml.php > sitemap.xml
 * URLs are built from SITE_URL in includes/config.php, so nothing is tied to
 * the machine the site runs on.
 * ---------------------------------------------------------------------------
 */
require_once __DIR__ . '/includes/config.php';

if (PHP_SAPI !== 'cli') {
    header('Content-Type: application/xml; charset=utf-8');
}

$pages = [];

/** Add a page with a priority and change frequency. */
$add = static function (string $file, string $priority, string $frequency) use (&$pages): void {
    $full = __DIR__ . '/' . ltrim($file, '/');
    $url  = $file === 'index.php' ? rtrim(SITE_URL, '/') . '/' : rtrim(SITE_URL, '/') . '/' . ltrim($file, '/');
    $url  = preg_replace('/\.php$/', '', $url) ?? $url;

    $mtime = is_file($full) ? (int) filemtime($full) : time();
    if ($mtime < 946684800) {
        $mtime = time();
    }

    $pages[] = [
        'loc'     => $url,
        'lastmod' => date('Y-m-d', $mtime),
        'priority'=> $priority,
        'freq'    => $frequency,
    ];
};

// Core pages
$add('index.php',  '1.0', 'weekly');
$add('about.php',  '0.8', 'monthly');
$add('services.php', '0.9', 'monthly');
$add('products.php', '0.9', 'monthly');
$add('projects.php', '0.7', 'monthly');
$add('guides.php',   '0.6', 'monthly');
$add('contact.php',  '0.9', 'monthly');

// Services
foreach (array_keys(all_services()) as $slug) {
    $add('services/' . $slug . '.php', '0.8', 'monthly');
}

// Products
foreach (array_keys(all_products()) as $slug) {
    $add('products/' . $slug . '.php', '0.8', 'monthly');
}

// Legal & utility
$add('privacy.php', '0.3', 'yearly');
$add('terms.php',   '0.3', 'yearly');
$add('sitemap.php', '0.2', 'yearly');

$xml  = '<?xml version="1.0" encoding="UTF-8"?>' . PHP_EOL;
$xml .= '<!-- Prospect Digital — generated by sitemap.xml.php on ' . date('c') . ' -->' . PHP_EOL;
$xml .= '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' . PHP_EOL;

foreach ($pages as $page) {
    $xml .= '  <url>' . PHP_EOL;
    $xml .= '    <loc>' . htmlspecialchars($page['loc'], ENT_XML1) . '</loc>' . PHP_EOL;
    $xml .= '    <lastmod>' . $page['lastmod'] . '</lastmod>' . PHP_EOL;
    $xml .= '    <changefreq>' . $page['freq'] . '</changefreq>' . PHP_EOL;
    $xml .= '    <priority>' . $page['priority'] . '</priority>' . PHP_EOL;
    $xml .= '  </url>' . PHP_EOL;
}

$xml .= '</urlset>' . PHP_EOL;

echo $xml;
